name: My first Github Action
on: [push]
jobs:
  print-hello-world:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World"
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14.0"
      - run: node -v
      - name: install node modules
        run: yarn
      - name: Deploying the project
        env:
          VERCEL_ORGid: Kp22NlopmLasGwmaCXKXKjuF
          VERCEL_PROJECTid: prj_dtVU7lp8bGN2VTk5RFpl2pMzFv0e
        run: yarn deploy
      - run: tree

