name: My first Github Action
on: [push]
jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World"
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14.0"
      - run: node -v
      - name: install node modules
        run: yarn
  test-app:
    needs: build-app
    runs-on: ubuntu-latest
    steps:
     - run: tree
     - run: echo "Job DOne"

